#!/bin/bash
DEVBOX=192.168.29.10
echo $1
dir=$(pwd)
if compgen -G "./*.gz" > /dev/null
then
	gunzip ./*.gz
fi

if compgen -G "./*.br" > /dev/null
then
	for file in ./*.br
	do
		node - <<'NODE' "${file}"
const fs = require('fs');
const zlib = require('zlib');

const source = process.argv[1];
const target = source.replace(/\.br$/i, '');

const input = fs.readFileSync(source);
const output = zlib.brotliDecompressSync(input);

fs.writeFileSync(target, output);
fs.rmSync(source);
NODE
	done
fi

version=$(git describe --abbrev=4 --dirty --always --tags)"-["$(git rev-parse --abbrev-ref HEAD)"]"
rm dist/spa/* -rf
# sed -e "s/Version:.*$/Version:${version}/" <src/layouts/RgbwwLayout.vue >src/layouts/RgbwwLayout.vue.1 && \
#	mv src/layouts/RgbwwLayout.vue src/layouts/RgbwwLayout.vue.2 && \
#	mv src/layouts/RgbwwLayout.vue.1 src/layouts/RgbwwLayout.vue && \
#  rm src/layouts/RgbwwLayout.vue.2

echo "deploying prod"
npx quasar build

cd $dir || exit
echo $version >dist/spa/VERSION
echo "VUE_APP_BUILD_NUMBER=$version" >.env
echo "deploying "
cat dist/spa/VERSION

echo "parameter: $1"
if [ "$1" == "local" ]
then
	echo "deploying locally"
	if [ ! -d ~/devel/esp_rgbww_firmware/webapp ]
	then
		mkdir ~/devel/esp_rgbww_firmware/webapp
	fi
	cp -auv dist/spa/* ~/devel/esp_rgbww_firmware/webapp/
	cp fileList.h ~/devel/esp_rgbww_firmware/include
	cd ~/devel/esp_rgbww_firmware || exit
	make -j8 flash
	cd $dir || exit
else
	echo "deplyoing to $DEVBOX"
	ssh $DEVBOX "if [ ! -d ~/devel/esp_rgbww_firmware/webapp ]; then mkdir ~/devel/esp_rgbww_firmware/webapp;fi"
	ssh $DEVBOX "rm -rf ~/devel/esp_rgbww_firmware/webapp/*"
	rsync -a dist/spa/ $DEVBOX:~/devel/esp_rgbww_firmware/webapp
	scp fileList.h $DEVBOX:~/devel/esp_rgbww_firmware/include
	if [ "$1" = "OTA" ]
	then
		ssh $DEVBOX "source ~/.smingrc;cd devel/esp_rgbww_firmware/;make -j8;./deployOta PART_LAYOUT=v1"
	else
		ssh $DEVBOX "source ~/.smingrc;cd devel/esp_rgbww_firmware/;make -j8 flash PART_LAYOUT=v1"
	fi
fi

