#define FILE_LIST(XX) \
	XX(VERSION, "VERSION") \
	XX(RgbwwLayout_css, "assets/RgbwwLayout.css.gz") \
	XX(RgbwwLayout_js, "assets/RgbwwLayout.js.gz") \
	XX(i18n_js, "assets/i18n.js.gz") \
	XX(index_css, "assets/index.css.gz") \
	XX(index_js, "assets/index.js.gz") \
	XX(pinconfig, "config/pinconfig.json") \
	XX(arrow_drop_down_svg, "icons/arrow_drop_down.svg.gz") \
	XX(badge_outlined_svg, "icons/badge_outlined.svg.gz") \
	XX(check_outlined_svg, "icons/check_outlined.svg.gz") \
	XX(close_outlined_svg, "icons/close_outlined.svg.gz") \
	XX(exposure_outlined_svg, "icons/exposure_outlined.svg.gz") \
	XX(favicon, "icons/favicon.ico") \
	XX(help_outlined_svg, "icons/help_outlined.svg.gz") \
	XX(hub_outlined_svg, "icons/hub_outlined.svg.gz") \
	XX(info_outlined_svg, "icons/info_outlined.svg.gz") \
	XX(lightbulb_outlined_svg, "icons/lightbulb_outlined.svg.gz") \
	XX(memory_outlined_svg, "icons/memory_outlined.svg.gz") \
	XX(menu_outlined_24_svg, "icons/menu_outlined_24.svg.gz") \
	XX(network_wifi_1_bar_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_1_bar_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_1_bar_locked_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_1_bar_locked_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_2_bar_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_2_bar_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_2_bar_locked_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_2_bar_locked_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_3_bar_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_3_bar_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_3_bar_locked_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_3_bar_locked_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_locked_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_locked_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(palette_outlined_svg, "icons/palette_outlined.svg.gz") \
	XX(report_problem_outlined_svg, "icons/report_problem_outlined.svg.gz") \
	XX(security_outlined_svg, "icons/security_outlined.svg.gz") \
	XX(settings_outlined_svg, "icons/settings_outlined.svg.gz") \
	XX(signal_wifi_statusbar_null_FILL0_wght400_GRAD0_opsz24_svg, "icons/signal_wifi_statusbar_null_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(star_outlined_svg, "icons/star_outlined.svg.gz") \
	XX(systemsecurityupdate_outlined_svg, "icons/systemsecurityupdate_outlined.svg.gz") \
	XX(tune_outlined_svg, "icons/tune_outlined.svg.gz") \
	XX(visibility_outlined_24_svg, "icons/visibility-outlined-24.svg.gz") \
	XX(visibility_off_outlined_svg, "icons/visibility_off_outlined.svg.gz") \
	XX(wb_incandescent_outline_24_svg, "icons/wb_incandescent_outline_24.svg.gz") \
	XX(wifi_lock_FILL0_wght400_GRAD0_opsz24_svg, "icons/wifi_lock_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(wifi_outlined_svg, "icons/wifi_outlined.svg.gz") \
	XX(index_html, "index.html.gz")
