#define FILE_LIST(XX) \
	XX(VERSION, "VERSION") \
	XX(RgbwwLayout_css, "assets/RgbwwLayout.css.gz") \
	XX(RgbwwLayout_js, "assets/RgbwwLayout.js.gz") \
	XX(i18n_js, "assets/i18n.js.gz") \
	XX(index_css, "assets/index.css.gz") \
	XX(index_js, "assets/index.js.gz") \
	XX(registerSvgIcon_js, "assets/registerSvgIcon.js.gz") \
	XX(pinconfig, "config/pinconfig.json") \
	XX(add_svg, "icons/add.svg.gz") \
	XX(add_circle_svg, "icons/add_circle.svg.gz") \
	XX(api_svg, "icons/api.svg.gz") \
	XX(arrow_drop_down_svg, "icons/arrow_drop_down.svg.gz") \
	XX(arrow_forward_svg, "icons/arrow_forward.svg.gz") \
	XX(article_svg, "icons/article.svg.gz") \
	XX(badge_outlined_svg, "icons/badge_outlined.svg.gz") \
	XX(blur_svg, "icons/blur.svg.gz") \
	XX(check_circle_svg, "icons/check_circle.svg.gz") \
	XX(check_outlined_svg, "icons/check_outlined.svg.gz") \
	XX(close_svg, "icons/close.svg.gz") \
	XX(close_outlined_svg, "icons/close_outlined.svg.gz") \
	XX(cloud_download_svg, "icons/cloud_download.svg.gz") \
	XX(cloud_upload_svg, "icons/cloud_upload.svg.gz") \
	XX(delete_svg, "icons/delete.svg.gz") \
	XX(delete_forever_svg, "icons/delete_forever.svg.gz") \
	XX(description_svg, "icons/description.svg.gz") \
	XX(drag_indicator_svg, "icons/drag_indicator.svg.gz") \
	XX(edit_svg, "icons/edit.svg.gz") \
	XX(error_svg, "icons/error.svg.gz") \
	XX(exposure_outlined_svg, "icons/exposure_outlined.svg.gz") \
	XX(favicon, "icons/favicon.ico") \
	XX(help_outlined_svg, "icons/help_outlined.svg.gz") \
	XX(home_svg, "icons/home.svg.gz") \
	XX(hub_outlined_svg, "icons/hub_outlined.svg.gz") \
	XX(info_svg, "icons/info.svg.gz") \
	XX(info_outlined_svg, "icons/info_outlined.svg.gz") \
	XX(light_group_svg, "icons/light_group.svg.gz") \
	XX(lightbulb_off_svg, "icons/lightbulb-off.svg.gz") \
	XX(lightbulb_on_svg, "icons/lightbulb-on.svg.gz") \
	XX(lightbulb_outlined_svg, "icons/lightbulb_outlined.svg.gz") \
	XX(linked_services_svg, "icons/linked_services.svg.gz") \
	XX(memory_outlined_svg, "icons/memory_outlined.svg.gz") \
	XX(menu_outlined_24_svg, "icons/menu_outlined_24.svg.gz") \
	XX(network_wifi_1_bar_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_1_bar_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_1_bar_locked_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_1_bar_locked_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_2_bar_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_2_bar_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_2_bar_locked_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_2_bar_locked_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_3_bar_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_3_bar_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_3_bar_locked_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_3_bar_locked_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(network_wifi_locked_FILL0_wght400_GRAD0_opsz24_svg, "icons/network_wifi_locked_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(open_in_new_svg, "icons/open_in_new.svg.gz") \
	XX(palette_outlined_svg, "icons/palette_outlined.svg.gz") \
	XX(photo_svg, "icons/photo.svg.gz") \
	XX(play_arrow_svg, "icons/play_arrow.svg.gz") \
	XX(refresh_svg, "icons/refresh.svg.gz") \
	XX(report_problem_outlined_svg, "icons/report_problem_outlined.svg.gz") \
	XX(restart_alt_svg, "icons/restart_alt.svg.gz") \
	XX(save_outlined_svg, "icons/save_outlined.svg.gz") \
	XX(scene_svg, "icons/scene.svg.gz") \
	XX(search_svg, "icons/search.svg.gz") \
	XX(security_outlined_svg, "icons/security_outlined.svg.gz") \
	XX(settings_outlined_svg, "icons/settings_outlined.svg.gz") \
	XX(signal_wifi_statusbar_null_FILL0_wght400_GRAD0_opsz24_svg, "icons/signal_wifi_statusbar_null_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(star_outlined_svg, "icons/star_outlined.svg.gz") \
	XX(swap_horiz_svg, "icons/swap_horiz.svg.gz") \
	XX(systemsecurityupdate_outlined_svg, "icons/systemsecurityupdate_outlined.svg.gz") \
	XX(telemetry_svg, "icons/telemetry.svg.gz") \
	XX(television_ambient_light_svg, "icons/television-ambient-light.svg.gz") \
	XX(timer_svg, "icons/timer.svg.gz") \
	XX(tune_outlined_svg, "icons/tune_outlined.svg.gz") \
	XX(visibility_outlined_24_svg, "icons/visibility-outlined-24.svg.gz") \
	XX(visibility_off_outlined_svg, "icons/visibility_off_outlined.svg.gz") \
	XX(warning_svg, "icons/warning.svg.gz") \
	XX(wb_incandescent_outline_24_svg, "icons/wb_incandescent_outline_24.svg.gz") \
	XX(wifi_lock_FILL0_wght400_GRAD0_opsz24_svg, "icons/wifi_lock_FILL0_wght400_GRAD0_opsz24.svg.gz") \
	XX(wifi_outlined_svg, "icons/wifi_outlined.svg.gz") \
	XX(index_html, "index.html.gz")
